image: docker/compose

services:
   - docker:dind

stages:
   - build
   - package
   
#variables:
#  DOCKER_HOST: tcp://docker:2375
#  DOCKER_DRIVER: overlay2
#  
#before_script:
#   - docker login -u $CI_REGISTRY_USER -p CI_REGISTRY_PASSWORD $CI_REGISTRY

maven-build:
   stage: build
   image: maven:latest
   script:
       - mvn -Dmaven.test.skip=true package

docker-build:
   stage: package
   script:
       - echo $CI_REGISTRY_USER
       - echo $CI_REGISTRY_PASSWORD 
       - echo $CI_REGISTRY
       - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
       - docker-compose build
