version: '3'
services:
  app:
    build: .
    image: esue1920/rest-jpa-example
    networks:
      - my-net
    depends_on:
      - db
    ports:
      - "80:8080"
    command: /wait-for-it.sh -t 120 db:3306 -- java -jar /app.jar --spring.datasource.url=$${DB_URL} --spring.datasource.username=$${DB_USER} --spring.datasource.password=$${DB_PASSWORD}
    
  db:
    image: mysql:latest
    volumes:
      - /home/deploy/app/dbstore:/var/lib/mysql
    networks:
      - my-net
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  
networks:
  my-net:
